version: 2
updates:
- package-ecosystem: npm
  directory: "/"
  schedule:
    interval: daily
  open-pull-requests-limit: 10
  ignore:
  - dependency-name: "@sanity/cli"
    versions:
    - 2.1.4
    - 2.2.5
    - 2.4.0
    - 2.5.0
    - 2.6.0
    - 2.7.2
    - 2.7.4
    - 2.8.0
  - dependency-name: "@sanity/core"
    versions:
    - 2.1.4
    - 2.3.3
    - 2.3.8
    - 2.4.0
    - 2.5.0
    - 2.6.0
    - 2.7.4
  - dependency-name: "@sanity/components"
    versions:
    - 2.1.4
  - dependency-name: react-intersection-observer
    versions:
    - 8.31.0
  - dependency-name: lodash
    versions:
    - 4.17.20
  - dependency-name: elliptic
    versions:
    - 6.5.3
  - dependency-name: lerna
    versions:
    - 3.22.1
  - dependency-name: handlebars
    versions:
    - 4.7.6
  - dependency-name: prettier-eslint-cli
    versions:
    - 5.0.0
